inherit_from: ../.rubocop.yml

require: rubocop-rspec

Metrics/BlockLength:
  Enabled: false # default: true

RSpec/ContextWording:
  Prefixes:
    - considering
    - when
    - with
    - without

RSpec/ExampleLength:
  Max: 12 # default: 5

RSpec/MultipleExpectations:
  Max: 4 # default: 1

RSpec/NamedSubject:
  Enabled: false # default: true

RSpec/NestedGroups:
  Max: 6 # default: 3

Style/BlockDelimiters:
  Enabled: false # default: true

Style/Documentation:
  Enabled: false # default: true

Style/MethodCallWithArgsParentheses:
  inherit_mode:
    merge:
      - IgnoredMethods
  IgnoredMethods:
    # rspec
    - after
    - and
    - around
    - before
    - context
    - describe
    - include_context
    - include_example
    - include_examples
    - it
    - it_behaves_like
    - not_to
    - or
    - shared_context
    - shared_examples
    - shared_examples_for
    - specify
    - to
    - to_not
