inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $logger
