before_install:
  - gem update --system
  - gem update bundler
before_script:
  - cp -f .rspec.travis .rspec
bundler_args: --without local
dist: trusty
language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
script:
  - bundle exec rake ci
sudo: false
